<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login_1</name>
   <tag></tag>
   <elementGuidId>7f144c64-c7c2-439e-b4fb-5e0795a1c191</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-0&quot;)/div[@class=&quot;row account-body&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-8 col-md-offset-2&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;loginform ng-dirty ng-touched ng-valid&quot;]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
